[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
senda_smartc = "B3DT8RTGLr4k34jidDKKDYaLZcsveSmMVD7CWfvq8bgn"

[programs.devnet]
senda_smartc = "B3DT8RTGLr4k34jidDKKDYaLZcsveSmMVD7CWfvq8bgn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./Turbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
